services:
  - type: web
    name: smash-bracket-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.oqtdlertvgmopnibrbiu:244510Hi#25@aws-1-us-east-2.pooler.supabase.com:6543/postgres
  - type: web
    name: smash-bracket-ui
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run " frontend.py" --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        fromService:
          name: smash-bracket-api
          type: web
          property: host
